@startuml uc13_automatic_detection
actor "Registered User" as User
participant "BBP App" as App
participant "BBP System" as Sys

autonumber

activate User

User -> App : start_automatically_monitored_activity(path)
activate App
App -> Sys : start_activity(path)
activate Sys
Sys -> Sys : retrieve_path_map(path)
Sys -->> App : path_map()
deactivate Sys
App -->> User : path_map()

' --------------------------

loop During activity
    App -> App : collect_sensor_data()
    App -> App : analyze_data_for_issues()
end

User -> App : stop_activity()

App -> App : generate_detected_issues_list()
App -->> User : display_issue_confirmation_form(issue_list)
deactivate App

User -> App : submit_confirmed_issues(issue_list)
activate App
App -> Sys : issue_report(path, issue_list)
activate Sys
Sys -->> App : issue_report_ack()
Sys -> Sys : update_path_status(issue_list)
App -->> User : issue_report_ack()

deactivate App

@enduml