@startuml uc1_sequence_diagram
hide footbox

actor User
participant "BBP App" as App

autonumber

activate User

User -> App : start_account_registration()

activate App
App -->> User : registration_form()
deactivate App

User -> App : submit_registration_form(name, surname, gender, birth_date, email_address, password)
activate App
App -> App : check_registration_info()

alt #ffe6e6 Invalid Email Format
    App -->> User : invalid_email_error()

else #ffe6e6 Email already used
    App -->> User : email_already_used_error()

else #e6ffe6 Valid form
    App -->> User : registration_link()
deactivate App

User -> App : registration_confirmation()
activate App
    alt #e6ffe6 Confirmation sent within 1 hour
        App -->> User : registration_ack()
    
    else #ffe6e6 Link expired
        App -->> User : invalid_registration_link()

    end
end
deactivate App

deactivate User
@enduml