@startuml uc6_sequence_diagram
actor User
participant "BBP App" as App

autonumber

activate User

User -> App : submit_route_points(start_point, destination)
activate App

App -> App : retrieve_nearby_paths(start_point, destination)
App -> App : rank_paths_by_score()

alt #ffe6e6 No paths found
    App -> App : create_path()
    note right: Refers to UC7 (Route discovery) TOOD review this
end

App -->> User : paths()
deactivate App

deactivate App
deactivate User
@enduml