@startuml uc8_sequence_diagram
actor "Unregistered User" as User
participant "BBP App" as App

autonumber

activate User

User -> App : start_ride(path)
activate App

App -> App : retrieve_path_map()
App -->> User : path_map()
deactivate App

loop Optional: during the trip
    User -> User : pause_trip()
    User -> User : resume_trip()
end

User -> User : complete_trip()

deactivate User
@enduml