@startuml uc8_sequence_diagram
hide footbox

actor "Unregistered User" as User
participant "BBP App" as App

autonumber

activate User

User -> App : start_ride(path)
activate App

loop Optional: during the trip
    User -> App : pause_trip()
    activate App
    App -->> User
    deactivate App
    User -> App : resume_trip()
    activate App
    App -->> User
    deactivate App
end

User -> App : complete_trip()
deactivate App

deactivate User
@enduml