@startuml uc9_sequence_diagram
hide footbox

actor "Registered User" as User
participant "BBP App" as App
participant "Weather Service" as Weather

autonumber

activate User

User -> App : start_ride(path)
activate App

loop Optional: during the trip
    User -> App : pause_trip()
    activate App
    App -->> User
    deactivate App
    User -> App : resume_trip()
    activate App
    App -->> User
    deactivate App
end

User -> App : activity_completion()
App -->> User : rating_form()
deactivate App

User -> App : submit_rating_form(rating)
activate App
App -> Weather : get_weather_conditions(timestamp, coordinates)
activate Weather

alt #e6ffe6 Weather service available
    Weather -->> App : weather_data()

else #ffe6e6 Weather service unavailable
    Weather -->> App : unavailable_weather_data_error()
    deactivate Weather
end
App -->> User : completed_activity_acknowledgement()
deactivate App

deactivate User
@enduml