@startuml Use Case Diagram
left to right direction

' --- Actors ---
:User: as u
:Registred user: as ru

:Mapping system: as ms
:Weather system: as ws

u <|--- ru

' --- Use Cases for User ---
(Account creation) as uc1
u --- uc1 : <<initiate>>

(Trip planning) as uc6
u --- uc6 : <<initiate>>

(Ride trip) as uc8
u --- uc8 : <<initiate>>
uc8 ...> uc6 :  <<include>>

(Route creation) as uc7
uc7 ...> uc6 : <<extends>>
uc7 --- ms : <<partecipate>>



' --- Use Cases for Registered User ---
(Login) as uc2
ru --- uc2 : <<inititate>>

(Account update) as uc3
ru --- uc3 : <<initiate>>

(Password reset) as uc4
ru --- uc4 : <<initiate>>

(Account deletion) as uc5
ru --- uc5 : <<initiate>>

(Activity trip) as uc9
ru ---- uc9 : <<initiate>>
uc8 <|- uc9

(Automatic activity monitoring) as uc10
ru --- uc10 : <<initiate>>
uc9 <. uc10 : <<extends>>
uc10 - ws: <<partecipates>>

(Manual route problem report) as uc11
ru --- uc11 : <<initiate>>

(Route fixup report) as uc12
ru --- uc12 : <<initiate>>

(Automatic route problem report) as uc13

uc13 ...> uc10 : <<extend>>  

(Activity history consultation) as uc14
ru --- uc14 : <<initiate>>

(Activity deletion from history) as uc15
ru --- uc15 : <<initiate>>

@enduml