@startuml domain_class_diagram
!theme plain

' switch to std UML notation for visibility
skinparam classAttributeIconSize 0


hide circle

' --- Abstract Class ---
abstract class "PublishableInformation" as pi {
+ user : User
+ path : BikePath
+ timestamp : datetime 
}

' --- Enumerations ---
' I dont' know if giving this effort on classifyng the cases is woth or not
enum "ObstacleType" as ot << enumeration >> { }

' Same thing as before
enum "StatusLevel" as sl << enumeration >> { }

' --- Classes ---
class "GeoPoint" as gp {
+ latitude : double
+ longitude : double
+ address : string
}

class "User" as u { }

class "RegisteredUser" as ru {
+ email : string
+ passwordHash : string
+ name : string
+ surname : string
+ birthDate : date
}

class "RUTrip" as rut {
+ avgSpeed : float
+ maxSpeed : float
+ minSpeed : float
+ altitudeDiff : float
+ isAutomaticallyMonitored : bool
}

class "UUTrip" as ut {
+ startingDatetime : datetime
+ endingDatetime : datetime
}

class "MeteorologicalInfo" as mi {
+ temperature: float 
+ windSpeed: float
+ condition: string
+ humidityPerc: int
}

class "SensorData" as sd {
+ timestamp: DateTime
+ accelerometerX: Float
+ accelerometerY: Float
+ accelerometerZ: Float
+ gpsLocation: GeoPoint
}

class "BikePath" as bp {
+ score : float
+ startPoint: GeoPoint
+ endPoint: GeoPoint
+ totalLenght : float
+ pathCoordinates: List<GeoPoint>
}

class "Obstacle" as o {
+ type: ObstacleType
+ description: String
}

class "RouteStatus" as rs {
+ status: StatusLevel
}

entity "MappingExtrenalSystem" as ms << Entity >>{
+ getPath(startingPoint: GeoPoint, endingPoint: GeoPoint): List<GeoPoint>
}

entity "WeatherExternalSystem" as ws << Entity >> {
+ getWeatherInfo(location: GeoPoint): List<string>
}

' --- Relationships ---
' Following relationships are listed in this way in order to make the diagram clearer

ms "*" ->  bp : "+creates "


bp "*" --> " 1" ut : "+involves "

rut --|> ut

u "*" --> "1 " ut : "+does"

ru "*" -> "1 " rut : "+records  "

u <|- ru

pi "1    " -- "*" bp : "+related"

pi "1" -- "0...*      " rut : "+generates"

gp <--o "*" bp : "+contains"

rs --|> pi
o --|> pi

sl ..> rs : <<uses>>
ot ..> o : <<uses>>

o "1 " --> gp : "+located"

pi "1 " <-- " *  " ru : "+publishes"

mi "1 " <--* "0...* " rut : " +contains"
ws " * " --> mi : "+creates"
rut "0...*" *- "  1" sd : "+generates"

@enduml