@startuml account_creation_sd
hide footbox

participant "Mobile App" as app
participant "Account API Gateway" as aapi
participant "Authentication Service" as auth
participant "Credentials DBMS" as dbc
participant "Email Proxy Service" as emailp
actor "Email Service Provider" as email
participant "Account DBMS" as dba
' concern about component activation at the end
activate app

app ->> aapi : create_account(name, surname gender, birthdate, emailAddress, psw)
activate aapi

'reactivate aapi
aapi ->> auth : create_account(name, surname, gender, birthdate, emailAddress, psw)
activate auth
auth -> dbc : query_user_exists(emailAddress)
activate dbc

alt #ffe6e6 email already used
    dbc -->> auth : match
    deactivate dbc
    auth -->> aapi : already_used_email_error
    deactivate auth
    aapi -->> app : already_used_email_error
    deactivate aapi
else #e6ffe6 valid form data
    activate dbc
    activate auth
    dbc -->> auth : no match
    deactivate dbc
    auth -> emailp : send_registration_link(emailAddress)
    activate emailp
    emailp -> email : send_email(emailAddress, registrationMailBody)
    activate email
    email -->> emailp : sent
    deactivate email
    emailp -->> auth : done
    deactivate emailp
    deactivate auth

    app ->> aapi : send_registration_confirmation()
    activate aapi
    note right 
        The user opens the link which 
        will be opened in the mobile app
    end note
    aapi ->> auth : send_registration_confirmation()
    activate auth
    alt #e6ffe6 confirmation sent within 1 hour
        auth ->> dbc : create_account_credentials(emailAddress, psw)
        activate dbc
        dbc -->> auth : created
        deactivate dbc
        auth ->> dba : create_account_info(emailAddress, name, surname, gender, birthdate)
        activate dba
        dba -->> auth : created
        deactivate dba
        auth -->> aapi : account_registration_succesful
        deactivate auth
        aapi -->> app : account_registration_succesful
        deactivate aapi

    ' fake message to handle activation
    aapi -[hidden]-> aapi
    activate aapi
    activate auth
    else #ffe6e6 link expired
        auth -->> aapi : link_expired_error
        deactivate auth
        aapi -->> app : link_expired_error
        deactivate aapi
    end
end

@enduml