@startuml sd4_password_reset
' Refers to UC4
hide footbox

participant "Mobile App" as app
participant "Account API Gateway" as aapi
participant "Authentication Service" as auth
participant "Credentials DBMS" as dbc
participant "Email Proxy Service" as emailp
actor "Email Service Provider" as email

activate app
app -> aapi : psw_reset_req(emailAddr)
activate aapi
aapi -> auth : psw_reset_req(emailAddr)
deactivate aapi
activate auth
auth -> dbc : query_user_exists(emailAddr)
deactivate auth
activate dbc
dbc -> dbc : fetch_account(emailAddr)
break #ffe6e6 no account for that email
    dbc -->> auth : no_match
    activate auth
    auth -->> aapi : no_account_error
    deactivate auth
    activate aapi
    aapi -->> app : no_account_error
    deactivate aapi
end
dbc -->> auth : userId
deactivate dbc
activate auth
auth ->> emailp : send_reset_link(emailAddr)
deactivate auth
activate emailp
emailp ->> email : send_email(emailAddr, pswResetMsg)
deactivate emailp
' you should improve this

app -> aapi : reset_psw_conf() 
note right
    The user opens the link received by email, which 
    will be opened by the mobile app
end note
activate aapi
aapi ->> auth : reset_psw_conf()
deactivate aapi
activate auth
break #ffe6e6 link expired
    auth -->> aapi : link_expired_error
    activate aapi
    aapi -->> app : link_expired_error
    deactivate aapi
end
auth -->> aapi : rest_psw_form
deactivate auth
activate aapi
aapi -->> app : reset_psw_form
deactivate aapi

app -> aapi : submit_new_psw(newPsw)
activate aapi
aapi ->> auth : update_psw(newPsw)
deactivate aapi
activate auth
auth ->> dbc : query_update_psw(userId, newPsw)
deactivate auth
activate dbc
dbc -> dbc : update_psw(userId, newPsw)
dbc -->> auth : done
deactivate dbc
activate auth
auth -->> aapi : done
deactivate auth
activate aapi
aapi -->> app : done
deactivate aapi
@enduml