@startuml sd7_unregistered_user_ride
' Refers to UC8

participant "Mobile App" as app
participant "Trip API Gateway" as tapi
participant "Path Inventory Service" as pi
participant "Path DMBS" as dbp

activate app
' ----- Consider to trim out this part
app -> tapi : get_path_map(pathId)
activate tapi
tapi ->> pi : get_path_map(pathId)
deactivate tapi
activate pi
pi ->> dbp : query_map(pathId)
deactivate pi
activate dbp
dbp -> dbp : fetch_map(pathId)
dbp -->> pi : pathMap
deactivate dbp
activate pi
pi -->> tapi : pathMap
deactivate pi
activate tapi
tapi -->> app : pathMap
deactivate tapi
' -----
opt stop/resume ride
    loop
        app -> app : pause_ride()
        app -> app : resume_ride()
    end
end

app -> app : complete_ride()
@enduml