@startuml sd8_registered_user_activity
' Refers to UC9
hide footbox

participant "Mobile App" as app
participant "Trip API Gateway" as tapi
participant "Activity Handler Service" as ahs
participant "Path Inventory Service" as pi
participant "Path DMBS" as dbp
participant "Weather Proy Service" as wps
actor "External Weather Service" as ews
participant "Activity History Service" as ah
participant "Activity DBMS" as dba
participant "Public Info Manager Service" as pim
participant "Public Info DBMS" as dbpi

activate app

' ----- Consider to trim out this part
app -> tapi : get_path_map(pathId)
activate tapi
tapi ->> ahs : get_path_map(pathId)
deactivate tapi
activate ahs
ahs ->> pi : get_path_map(pathId)
deactivate ahs
activate pi
pi ->> dbp : query_map(pathId)
deactivate pi
activate dbp
dbp -> dbp : fetch_map(pathId)
dbp -->> pi : pathMap
deactivate dbp
activate pi
pi -->> ahs : pathMap
deactivate pi
activate ahs
ahs -->> tapi : pathMap
deactivate ahs
activate tapi
tapi -->> app : pathMap
deactivate tapi
' -----

opt stop/resume trip
    loop
        app -> app : pause_activity()
        app -> app : resume_activity()
    end
end

app -> app : complete_ride()
app -> app : score_path()
app -> tapi: save_act(save_activity(userId, pathId, date, startTime, endTime, score)
activate tapi
tapi ->> ahs : save_act(userId, pathId, date, startTime, endTime, score)
deactivate tapi
activate ahs
' retrive wetaher info
ahs ->> pi : get_paht_loc(pathId)
deactivate ahs
activate pi
pi ->>  dbp : query_loc(pathId)
deactivate pi
activate dbp
dbp -> dbp : fecth_loc(pathId)
dbp -->> pi : pathLocation
deactivate dbp
activate pi
pi -->> ahs : pathLocation
deactivate pi
activate ahs
ahs ->> wps : get_weat_info(pathLocation)
deactivate ahs
activate wps
wps ->> ews : get_weat_info(pathLocation)
deactivate wps
activate ews
ews -> ews : fetch_weat_info(pathLocation)
alt #dff7e5 weather info available
    ews -->> wps : weatherInfo
    activate wps
    wps -->> ahs : weatherInfo
    deactivate wps
    activate ahs
else #ffe6e6 waether info unavailable
    ews -->> wps : unavailable
    deactivate ews
    activate wps
    wps -->> ahs : unavailable
    deactivate wps    
end

ahs ->> ah : save_act(userId, pathId, activityInfo)
note left
activityInfo contains date, startTime, 
endTime and possibly wetaherInfo
end note
deactivate ahs
activate ah 
ah ->> dba : query_save_act(userId, pathId, activityInfo)
deactivate ah 
activate dba
dba -> dba : insert_act(userId, pathId, activityInfo)
dba -->> ah : actId
deactivate dba
activate ah
ah -->> ahs : actId
deactivate ah
activate ahs

ahs ->> pim : save_score(userId, pathId, actId)
deactivate ahs 
activate pim
pim ->> dbpi : query_save_score(userId, pathId, actId)
deactivate pim 
activate dbpi
dbpi -> dbpi : insert_score(userId, pathId, actId)
dbpi -->> pim : done
deactivate dbpi
activate pim
pim -->> ahs : done
deactivate pim
activate ahs

ahs -->> tapi : done
deactivate ahs
activate tapi
tapi -->> app : done
deactivate tapi

@enduml