@startuml sd8_registered_user_activity
' Refers to UC10, 13
hide footbox

skinparam sequence {
    ReferenceBackgroundColor #fcf8e1
}

participant "Mobile App" as app
participant "Trip API Gateway" as tapi
participant "Activity Handler Service" as ahs
participant "Weather Proy Service" as wps
actor "External Weather Service" as ews
participant "Path Subsystem" as pss
participant "Activity Subsystem" as ass 
participant "Public Info Subsystem" as piss

activate app
app -> app :start_activity()
opt stop/resume trip
    loop
        app -> app : pause_activity()
        app -> app : resume_activity()
    end
end
app -> app : complete_ride()
app -> app : score_path()
app -> app : confirm_det_issue()
app -> tapi: save_act(save_activity(userId, pathId, date, startTime, endTime, score, List<detIssue>)
activate tapi
tapi ->> ahs : save_act(userId, pathId, date, startTime, endTime, score, List<detIssue>)
deactivate tapi

activate ahs
ahs ->> wps : check_av()
ref over wps, ews, pss : Refer to SD 7.1-Weather Info Retrivalactivate 

par #e1f4fc 
    ahs ->> ass : save_act(userId, pathId, activityInfo)
    ref over  ass : Refer to SD 7.2-Store Activity
else
    ahs ->> piss : save_score(userId, pathId, actId)
    ref over piss : Refer to SD 7.3-Store Score
else
    ahs ->> piss : save_issue(userId, pathId, List<detIssue>)
    ref over piss : Refer to SD 8.1-Store Automatic Issue
end
ahs -->> tapi : done
deactivate ahs
activate tapi
tapi -->> app : done
deactivate tapi

@enduml