@startuml sd1-3_store_account_credentials
hide footbox

participant "Account Creation Service" as acs
participant "Authentication Service" as auth
participant "Credentials  DBMS" as dbc

acs ->> auth : create_acc_cred(newUserId, emailAddr, psw)
deactivate acs
activate auth
auth ->> dbc : query_insert_cred(newUserId, emailAddr, psw)
deactivate auth
activate dbc
dbc -> dbc : insert_cred(newUserI, emailAddr, psw)
dbc -->> auth : done
deactivate dbc
activate auth
auth -->> acs : done
deactivate auth
activate acs

@enduml